### ISSUE TITLE
Commas first

### ISSUE THREAD

**Issue by anka-213** [parsonsmatt/fourmolu#16]
Since we have opened the pandoras box of configuration, would it be possible to add an option for having commas first in lists and records?

It is the one thing that annoys me whenever I use ormolu and it is the opposite of how all the rest of the Haskell community does it<sup>e.g. [1](https://kowainik.github.io/posts/2019-02-06-style-guide) [2](https://github.com/tibbe/haskell-style-guide/blob/master/haskell-style.md)</sup>. The motivation seems fairly lacking, since Haskell afaik doesn't support trailing commas in most cases and now it forces you to manually type commas when appending a line to a list.

How tightly integrated is the choice of commas last in the design of the program? Would adding this configuration lead to a lot of extra complexity?

**Comment by georgefst** [comment]
This is definitely something I'd like to see. Indeed, it's one of the two or three things holding me back from actually using Fourmolu on most of my projects.

FWIW, the decision is explained in the first path of the 'Commas' section [here](https://www.tweag.io/blog/2019-10-11-ormolu-first-release/). I personally couldn't care less about consistency between expressions and patterns here, not least because I don't imagine ever wanting to use a multiline list or tuple pattern. But I suspect it means the code is being reused between both cases, so we'd have to split that up, but I don't imagine it being too difficult.

PRs very welcome, but this is on my radar anyway.

**Comment by anka-213** [comment]
Yes, that was exactly the motivation I found lacking. I couldn't care less about that consistency either.

**Comment by parsonsmatt** [comment]
strong agree

**Comment by georgefst** [comment]
I've just discovered that there's a google [fork](https://github.com/google/ormolu) of Ormolu, which [implements this](https://github.com/google/ormolu/commit/5a36b8b6ef85b587bbf6e8cd5ecb7754fed7461d).

Implemented, in fact, by the lead developer of Ormolu...

The discussion leading to that has presumably gone on behind closed doors, and I'm unsure what ties Tweag and Google have. But clearly someone there shares our opinions.

Anyway, if nothing else, it gives us some tips on implementation.
