### ISSUE TITLE
Stackage?

### ISSUE THREAD

**Issue by brandon-leapyear** [parsonsmatt/fourmolu#73]
Are there any plans to register this on Stackage?

**Comment by georgefst** [comment]
It was mentioned way back in #1. Since then, I've taken over most of the maintenance, and I don't use Stack.

Would you be interested at all in becoming a co-maintainer, with responsibility for Stackage maintenance? I'm hoping to be able to start tackling some of the open issues in the next few weeks, but we could really do with another pair of hands.

**Comment by brandon-leapyear** [comment]
Sure, I can handle Stackage maintenance!

**Comment by brandon-leapyear** [comment]
Can you add my personal account? @brandonchinn178

**Comment by georgefst** [comment]
Great! I should double check that @parsonsmatt is happy? (I'm not sure if I have permissions anyway)

**Comment by brandonchinn178** [comment]
Let me know! I have the PR ready to go
https://github.com/commercialhaskell/stackage/pull/5932

**Comment by parsonsmatt** [comment]
Oh, sorry for missing this!
